import { NextResponse } from "next/server";
export const runtime="nodejs";export const dynamic="force-dynamic";export const revalidate=0;
type Score={inning:string;r:number|null;w:number|null;o:string};
type Match={id:string;name:string;teams:string[];teamInfo:{name:string}[];score:Score[];status:string;matchStarted:boolean;matchEnded:boolean;source:string;date?:string;matchType?:string;venue?:string};
const H={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36","accept-language":"en-US,en;q=0.9","referer":"https://www.cricbuzz.com/"};
const clean=(v:any)=>String(v??"").replace(/<[^>]*>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&#39;/g,"'").replace(/\s+/g," ").trim();
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const split=(s:string)=>{const m=s.match(/^(.+?)\s+vs\.?\s+(.+?)(?:,|$)/i);return m?[m[1].trim(),m[2].trim()]:[]};
const finished=(s:any)=>/\b(?:won by|won$|complete|completed|match drawn|drawn|no result|abandoned|abandon|cancelled|concluded|final result|match over)\b/i.test(clean(s));
const live=(s:any)=>/\b(?:live|in progress|inprogress|innings break|stumps|rain|delay|need \d+|trail by|lead by|session|opt to)\b/i.test(clean(s));
function scores(raw:any,teams:string[]):Score[]{const out:Score[]=[];const add=(x:any,i:number)=>{const txt=clean(x?.score??x);const m=txt.match(/(\d+)\s*[-/]\s*(\d+)(?:\s*\(([^)]+)\))?/);const r=num(x?.runs??x?.r??x?.teamScore??m?.[1]);const w=num(x?.wickets??x?.w??x?.wkts??x?.teamWkts??m?.[2]);const o=clean(x?.overs??x?.o??x?.ov??m?.[3]);if(r!==null||w!==null||o)out.push({inning:clean(x?.team??x?.teamName??x?.inning??teams[i]??"Innings"),r,w,o});};const candidates=[raw?.score,raw?.scores,raw?.score?.innings,raw?.innings].filter(Boolean);for(const c of candidates){if(Array.isArray(c))c.forEach(add);else if(typeof c==="object"){const vals=Object.values(c);if(vals.some(v=>typeof v==="object"))vals.forEach(add);else add(c,0)}else add(c,0)}const seen=new Set<string>();return out.filter(x=>{const k=`${x.inning}|${x.r}|${x.w}|${x.o}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,4)}
function native(data:any):Match[]{const rows=Array.isArray(data?.matches)?data.matches.map((m:any)=>[m?.id??m?.matchId,m]):data?.matches&&typeof data.matches==="object"?Object.entries(data.matches):[];return (rows as any[]).map(([key,raw])=>{const h=raw?.header??raw?.matchHeader??{};const id=clean(raw?.id??raw?.matchId??raw?.match_id??key);const teams=[clean(raw?.team1?.name??raw?.team1?.teamName),clean(raw?.team2?.name??raw?.team2?.teamName)].filter(Boolean);const desc=clean(h?.matchDescription??h?.matchDesc??raw?.matchDescription??raw?.description);const status=clean(h?.status??raw?.status??raw?.statusText??h?.state??raw?.state);const sc=scores(raw,teams);const end=finished(status);const explicitLive=live(status)||/inprogress|live/i.test(clean(h?.state??raw?.state));
const start=!end&&explicitLive;if(!/^\d+$/.test(id)||!start||end)return null;return{id,name:teams.length===2?teams.join(" vs ")+(desc?", "+desc:""):clean(raw?.name??desc)||"Live Match",teams,teamInfo:teams.map(name=>({name})),score:sc,status:status||"Live",matchStarted:true,matchEnded:false,source:"cricbuzz-match-api",matchType:desc}}).filter(Boolean) as Match[]}
function htmlMatches(html:string):Match[]{const out=new Map<string,Match>();const re=/<a\b[^>]*href=["']([^"']*\/live-cricket-(?:scores|scorecard)\/(\d+)[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){const id=m[2],near=clean(html.slice(Math.max(0,m.index-500),Math.min(html.length,m.index+1200)));let name=clean(m[3]);if(!/\bvs\.?\b/i.test(name)){const z=near.match(/([A-Za-z][A-Za-z .&'()\-]{1,70}?\s+vs\.?\s+[A-Za-z][A-Za-z .&'()\-]{1,70}?)(?=\s+(?:LIVE|\d+(?:st|nd|rd|th)\s+Match|Day\s+\d)|\s*[|,]|$)/i);if(z)name=z[1].trim()}if(!name||!live(near)||finished(near)||/\/result\\s*:\|won by\|match over\|match completed\/i/.test(near))continue;const teams=split(name);out.set(id,{id,name:name.replace(/\s+LIVE\s*$/i,"").trim(),teams,teamInfo:teams.map(name=>({name})),score:scores({score:near},teams),status:near.match(/(?:Need|Lead by|Trail by|Stumps|Rain|Live)[^.]{0,120}/i)?.[0]||"Live",matchStarted:true,matchEnded:false,source:"cricbuzz-html"})}return[...out.values()]}
async function get(url:string){const r=await fetch(url,{cache:"no-store",headers:{...H,accept:"application/json,text/html;q=0.9,*/*;q=0.8"}});const body=await r.text();if(!r.ok)throw new Error("HTTP "+r.status);return body}
export async function GET(){const debug:any[]=[];let matches:Match[]=[];try{matches=native(JSON.parse(await get("https://www.cricbuzz.com/match-api/livematches.json")));debug.push({source:"match-api",ok:true,count:matches.length})}catch(e){debug.push({source:"match-api",ok:false,error:e instanceof Error?e.message:"failed"})}if(!matches.length){for(const url of ["https://www.cricbuzz.com/cricket-match/live-scores","https://www.cricbuzz.com/cricket-schedule/series/all/liveStream","https://www.cricbuzz.com/cricket-series"]){try{const found=htmlMatches(await get(url));debug.push({source:url,ok:true,count:found.length});if(found.length){matches=found;break}}catch(e){debug.push({source:url,ok:false,error:e instanceof Error?e.message:"failed"})}}}return NextResponse.json({ok:true,data:matches,debug,fetchedAt:new Date().toISOString()},{headers:{"Cache-Control":"no-store, max-age=0"}})}