"use client";
import {useEffect,useState} from "react";
function value(v:any,fallback="—"){return v===undefined||v===null||v===""?fallback:String(v)}
function player(r:any){return r?.batsman||r?.batter||r?.name||r?.bowler||r?.player||"Unknown player"}
export default function ScorecardClient({id}:{id:string}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function refresh(){setLoading(true);try{const r=await fetch("/api/score?score="+encodeURIComponent(id)+"&ts="+Date.now(),{cache:"no-store"});const j=await r.json();if(j?.status!=="success")throw new Error(j?.message||"Scorecard unavailable");setData(j);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load scorecard")}finally{setLoading(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,30000);return()=>clearInterval(t)},[id]);
 const innings=Array.isArray(data?.scorecard)?data.scorecard:[];
 return <main className="mx-auto min-h-screen max-w-6xl px-4 py-8">
  <a href={"/match/"+id} className="text-sm font-bold text-green-400">← Match Center</a>
  <div className="mt-6 flex items-end justify-between gap-4"><div><p className="text-xs font-black tracking-[.2em] text-red-400">🔴 LIVE SCORECARD</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{data?.name||"Detailed Scorecard"}</h1><p className="mt-3 text-slate-400">{data?.matchStatus||"Loading live match details…"}</p></div><button onClick={refresh} disabled={loading} className="rounded-xl border border-green-500/40 px-4 py-3 text-sm font-black text-green-400 disabled:opacity-50">{loading?"Refreshing…":"↻ Refresh"}</button></div>
  {loading&&!data?<div className="card mt-8 rounded-3xl p-7"><p className="font-black">Loading complete scorecard…</p></div>:innings.length?<div className="mt-8 space-y-8">{innings.map((inn:any,i:number)=>{const batting=Array.isArray(inn.batting)?inn.batting:[],bowling=Array.isArray(inn.bowling)?inn.bowling:[],total=inn.total||{};return <section key={i} className="card overflow-hidden rounded-3xl"><div className="border-b border-[#20364d] p-6"><p className="text-xs font-black tracking-[.18em] text-green-400">INNINGS {i+1}</p><h2 className="mt-2 text-2xl font-black">{inn.inning||"Innings "+(i+1)}</h2><div className="mt-4 flex flex-wrap gap-3">{total.runs!==undefined&&<span className="rounded-full bg-green-500/10 px-3 py-2 font-black text-green-300">{value(total.runs)}/{value(total.wickets,"0")}</span>}{total.overs!==undefined&&<span className="rounded-full bg-white/[.04] px-3 py-2 text-sm text-slate-300">{value(total.overs)} overs</span>}{inn.extras?.runs!==undefined&&<span className="rounded-full bg-white/[.04] px-3 py-2 text-sm text-slate-300">Extras {inn.extras.runs}</span>}</div></div>
  {batting.length>0&&<div className="p-6"><h3 className="text-lg font-black">Batting</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[#20364d] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-3 py-3">Batter</th><th className="px-3 py-3">Dismissal</th><th className="px-3 py-3 text-right">R</th><th className="px-3 py-3 text-right">B</th><th className="px-3 py-3 text-right">4s</th><th className="px-3 py-3 text-right">6s</th><th className="px-3 py-3 text-right">SR</th></tr></thead><tbody>{batting.map((r:any,j:number)=><tr key={j} className="border-b border-white/[.04]"><td className="px-3 py-4 font-bold">{player(r)}</td><td className="max-w-[280px] px-3 py-4 text-xs text-slate-400">{value(r.dismissal)}</td><td className="px-3 py-4 text-right font-black">{value(r.runs)}</td><td className="px-3 py-4 text-right">{value(r.balls)}</td><td className="px-3 py-4 text-right">{value(r.fours)}</td><td className="px-3 py-4 text-right">{value(r.sixes)}</td><td className="px-3 py-4 text-right">{value(r.strikeRate)}</td></tr>)}</tbody></table></div></div>}
  {bowling.length>0&&<div className="border-t border-[#20364d] p-6"><h3 className="text-lg font-black">Bowling</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-[#20364d] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-3 py-3">Bowler</th><th className="px-3 py-3 text-right">O</th><th className="px-3 py-3 text-right">M</th><th className="px-3 py-3 text-right">R</th><th className="px-3 py-3 text-right">W</th><th className="px-3 py-3 text-right">NB</th><th className="px-3 py-3 text-right">WD</th><th className="px-3 py-3 text-right">Econ</th></tr></thead><tbody>{bowling.map((r:any,j:number)=><tr key={j} className="border-b border-white/[.04]"><td className="px-3 py-4 font-bold">{player(r)}</td><td className="px-3 py-4 text-right">{value(r.overs)}</td><td className="px-3 py-4 text-right">{value(r.maidens)}</td><td className="px-3 py-4 text-right">{value(r.runs)}</td><td className="px-3 py-4 text-right font-black text-green-300">{value(r.wickets)}</td><td className="px-3 py-4 text-right">{value(r.noBalls)}</td><td className="px-3 py-4 text-right">{value(r.wides)}</td><td className="px-3 py-4 text-right">{value(r.economy)}</td></tr>)}</tbody></table></div></div>}
  </section>})}</div>:<div className="card mt-8 rounded-3xl p-7"><p className="text-lg font-black">Detailed scorecard is not available yet</p><p className="mt-2 text-sm text-slate-400">{error||"The score source has not returned player-by-player data yet."}</p><button onClick={refresh} className="mt-5 rounded-xl bg-green-500 px-4 py-2 font-black text-slate-950">Try again</button></div>}
 </main>
}